### ISSUE TITLE
Need to keep track of the different volumes that released the token

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/atd#1]
One thing is missing and I feel it's quite important.
This contract is great to distribute the token but if we want to audit and make sure that the distribution respected the rules we need to also have access to the following informations:

- volume for a certain day 
- number of tokens released for a specific address

I would add the following APIs instead of the current one:
- addDailyVolume: Append the daily volume and pre-calculate the allowance to withdraw for this day with a flag withdrawn at false

- withdraw: get the available token and transfer them based on the previous one calculated with the addDailyVolume

This way we can withdraw multiple time a day or cumulate for few days before withdraw

**Comment by NicolasMahe** [comment]
> * volume for a certain day

This is recorded with the event `Distributed`, but yeah, the smart contract itself cannot access past events and thus cannot return the total distributed token with a function.
I will record the transfers in a structure on the smart contract.

```
  event Distributed(uint256 dailyTradedVolume, uint256 amount);
```

> * number of tokens released for a specific address

I wanted to use the ERC20 `Transfer` event, but it may not be the easiest way to check by hand..
I will also record the transfers in a structure on the smart contract.

> This way we can withdraw multiple time a day or cumulate for few days before withdraw

I really think doing the withdraw directly is way more transparent and easier for anyone to check the numbers of tokens released by simply looking a the balance of the cold wallets.

**Comment by antho1404** [comment]
- [x] daily volume for a certain day: OK with events
- [x] withdraw and set volume in the same transaction: OK
- [ ] number of tokens released for a specific address per day

Just to clarify on this last point:
There is no way to get it directly from the ATD contract, the function `getPastEvents` returns only the events of the smart contract (even if we add the ABI of the token in the definition)

![image](https://user-images.githubusercontent.com/1783126/55335512-661d5680-54c5-11e9-9a6f-b44d94f875b9.png)

So here we have to filter all the events `Distributed` and fetch the receipt for each transaction to extract the result of the `Transfer` event. I feel it's quite a lot where we could simply add a new event `DistributedFrom(from, to, amount)` that we will be able to retrieve easily with `getPastEvents('DistributedFrom')` with even filter possible on the sender/receiver.

This is not a big change in the smart contract and doesn't change anything but will help a lot the development of the dashboard.

**Comment by NicolasMahe** [comment]
Individual events added: https://github.com/mesg-foundation/atd/commit/c421979b3ca355c3790f7699de23638c4fbe0025
