### ISSUE TITLE
Check for provider's network

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/atd#44]
Related to PR https://github.com/mesg-foundation/atd/pull/43

If the visitor has metamask but it's setup on the wrong network, an ugly and non descriptive error is displayed:
![image](https://user-images.githubusercontent.com/5823445/60336934-e3c10780-99cb-11e9-9c8c-416db35de7f1.png)

The artifacts/index.js should check the provider network configuration and if not set on the right one, throw an error that say something like:
"Please switch to Ethereum Mainnet and reload the page."

**Comment by NicolasMahe** [comment]
Metamask docs about this: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.networkversion

**Comment by patjanawat** [comment]
> Related to PR #43
> 
> If the visitor has metamask but it's setup on the wrong network, an ugly and non descriptive error is displayed:
> ![image](https://user-images.githubusercontent.com/5823445/60336934-e3c10780-99cb-11e9-9c8c-416db35de7f1.png)
> 
> The artifacts/index.js should check the provider network configuration and if not set on the right one, throw an error that say something like:
> "Please switch to Ethereum Mainnet and reload the page."

I see the issue when we trying to get LockWallet on Ropsten network (Lockwallet is empty) for calculating the daily percentage

Problem:
Because distributionConfigsLength is null so can't convert type by toNumber

Solution:
parseInt(await atd.methods.distributionConfigsLength().call()) || 0 

Are you agree?

**Comment by NicolasMahe** [comment]
> The artifacts/index.js should check the provider network configuration and if not set on the right one, throw an error that say something like:
> "Please switch to Ethereum Mainnet and reload the page."

**Comment by patjanawat** [comment]
> No. The dashboard should simply throw an error:
> 
> > The artifacts/index.js should check the provider network configuration and if not set on the right one, throw an error that say something like:
> > "Please switch to Ethereum Mainnet and reload the page."

Resolved.
